import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const out = resolve(root, 'workflows');
const check = process.argv.includes('--check');

const specs = [
  {
    slug: 'linkedin-to-crm',
    name: 'Phase 8 - LinkedIn to CRM v1',
    eventType: 'linkedin.crm_lead_candidate.v1',
    actor: 'n8n-linkedin-crm',
    owner: 'CRM Operations',
    reviewer: 'crm_manager',
    capability: 'create_crm_lead_draft.v1',
    profile: 'draft-operations',
    sourceCode: `must(/^https:\\/\\/([a-z]+\\.)?linkedin\\.com\\//.test(body.source?.url || ''), 'source_url');must(['operator_url','approved_export'].includes(body.source?.capture_mechanism),'capture_mechanism');must(!Number.isNaN(Date.parse(body.source?.captured_at||'')),'captured_at');must(typeof body.source?.provenance==='string'&&body.source.provenance.length>=3&&body.source.provenance.length<=512,'provenance');`,
    extractValidation: `const e=result.extraction;must(e&&typeof e==='object','extraction');for(const k of ['organization','person','stated_need','location']){const f=e[k];must(f&&typeof f==='object'&&typeof f.confidence==='number'&&Array.isArray(f.evidence_refs),k);}must(Array.isArray(e.facts)&&Array.isArray(e.inferences),'fact_inference_separation');`,
    reviewValidation: `must(result.duplicates&&Array.isArray(result.duplicates.partner_candidates)&&Array.isArray(result.duplicates.lead_candidates)&&typeof result.duplicates.match_explanation==='string','duplicate_evidence');must(result.review?.state==='pending'&&result.review?.owner==='CRM Operations','review_state');`,
    readCode: `const e=$('Validate Extraction').first().json.extraction;const org=e.organization.value??'';const person=e.person.value??'';const context={allowed_company_ids:[1],force_company:1};return [{json:{instance:'ocloud-staging',model:'res.partner',domain:['|',['company_id','=',false],['company_id','=',1],['name','ilike',String(org||person).slice(0,200)]],fields:['id','name','company_id'],limit:20,context}},{json:{instance:'ocloud-staging',model:'crm.lead',domain:[['company_id','=',1],['name','ilike',String(org||person).slice(0,200)]],fields:['id','name','partner_name','company_id','type'],limit:20,context}}];`,
    createCode: `
const p = input.payload;
closed(p, ['title','organization','contact_name','email','phone','description','evidence_ref','idempotency_key']);
must(typeof p.title === 'string' && p.title.trim().length >= 3 && p.title.length <= 200, 'title');
for (const [k,n] of Object.entries({organization:200,contact_name:200,email:254,phone:50,description:4000})) must(p[k] === null || (typeof p[k] === 'string' && p[k].length >= 1 && p[k].length <= n), k);
must(typeof p.evidence_ref === 'string' && p.evidence_ref.length >= 3 && p.evidence_ref.length <= 512, 'evidence_ref');
must(p.idempotency_key===capabilityKey('crm-lead',{capability:'create_crm_lead_draft.v1',instance_id:'ocloud-staging',company_id:1,title:p.title,organization:p.organization,contact_name:p.contact_name,email:p.email,phone:p.phone,description:p.description,evidence_ref:p.evidence_ref}),'idempotency_key');
const values={name:p.title.trim(),type:'lead',company_id:1};
for (const [target,source] of Object.entries({partner_name:'organization',contact_name:'contact_name',email_from:'email',phone:'phone',description:'description'})) if (p[source] !== null) values[target]=p[source];
return operation('crm.lead', values);`,
    verify: `{instance:'ocloud-staging',model:'crm.lead',ids:[$json.id],fields:['id','company_id','type'],context:{allowed_company_ids:[1],force_company:1}}`,
    duplicate: `{instance:'ocloud-staging',model:'crm.lead',domain:[['company_id','=',1],['type','=','lead'],['name','=',String($('Consume Approval').first().json.payload.title).trim()]],fields:['id','company_id','type'],limit:2,context:{allowed_company_ids:[1],force_company:1}}`,
    postcondition: `must(id(record.company_id)===1&&record.type==='lead','crm_lead_postcondition');`,
  },
  {
    slug: 'gmail-vendor-invoice',
    name: 'Phase 8 - Gmail Vendor Invoice v1',
    eventType: 'gmail.vendor_invoice_received.v1',
    actor: 'n8n-vendor-invoice',
    owner: 'Accounts Payable Operations',
    reviewer: 'accounts_payable_manager',
    capability: 'prepare_vendor_bill_draft.v1',
    profile: 'draft-operations',
    sourceCode: `const s=body.source;must(s?.filter_ref==='secret://n8n/gmail/vendor-invoice-filter','mailbox_filter');must(/^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$/.test(s?.mailbox||''),'mailbox');must(/^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$/.test(s?.sender||''),'sender');must(typeof s?.message_id==='string'&&s.message_id.length>=3&&s.message_id.length<=512,'message_id');const a=s?.attachments;must(Array.isArray(a)&&a.length>=1&&a.length<=10,'attachments');for(const x of a){must(['application/pdf','image/jpeg','image/png'].includes(x.mime_type),'mime_type');must(Number.isInteger(x.size_bytes)&&x.size_bytes>0&&x.size_bytes<=20000000,'size_bytes');must(x.malware_status==='clean','malware_status');must(/^sha256:[0-9a-f]{64}$/.test(x.content_hash||''),'attachment_hash');}`,
    extractValidation: `const e=result.extraction;must(e&&typeof e==='object','extraction');for(const k of ['vendor_name','vendor_reference','invoice_date','due_date','currency','subtotal_minor','tax_minor','total_minor']){const f=e[k];must(f&&typeof f==='object'&&typeof f.confidence==='number'&&f.confidence>=0&&f.confidence<=1&&typeof f.evidence_ref==='string',k);}must(Array.isArray(e.lines)&&e.lines.length>=1&&e.lines.every(x=>typeof x.confidence==='number'&&typeof x.evidence_ref==='string'),'invoice_lines');`,
    reviewValidation: `must(result.resolution?.company_id===1&&Object.hasOwn(result.resolution,'vendor_id')&&typeof result.resolution.duplicate_vendor_reference==='boolean','vendor_resolution');must(result.matching&&Array.isArray(result.matching.purchase_orders)&&Array.isArray(result.matching.receipts)&&Array.isArray(result.matching.discrepancies),'invoice_matching');must(result.review?.state==='pending'&&result.review?.owner==='Accounts Payable Operations'&&result.review?.posting_allowed===false,'review_state');`,
    readCode: `const e=$('Validate Extraction').first().json.extraction;const vendor=String(e.vendor_name.value||'').slice(0,200);const ref=String(e.vendor_reference.value||'').slice(0,100);const context={allowed_company_ids:[1],force_company:1};return [{json:{instance:'ocloud-staging',model:'res.partner',domain:['|',['company_id','=',false],['company_id','=',1],['name','ilike',vendor]],fields:['id','name','company_id','supplier_rank'],limit:20,context}},{json:{instance:'ocloud-staging',model:'res.company',domain:[['id','=',1]],fields:['id','currency_id'],limit:1,context}},{json:{instance:'ocloud-staging',model:'account.account',domain:[['company_ids','in',[1]],['account_type','in',['expense','expense_direct_cost']]],fields:['id','code','account_type','company_ids'],limit:20,context}},{json:{instance:'ocloud-staging',model:'account.move',domain:[['company_id','=',1],['move_type','=','in_invoice'],['ref','=',ref]],fields:['id','partner_id','ref','state','company_id','move_type','currency_id'],limit:20,context}},{json:{instance:'ocloud-staging',model:'purchase.order',domain:[['company_id','=',1],['partner_id.name','ilike',vendor]],fields:['id','name','partner_id','currency_id','state','order_line'],limit:50,context}},{json:{instance:'ocloud-staging',model:'stock.picking',domain:[['company_id','=',1],['partner_id.name','ilike',vendor]],fields:['id','name','origin','state','move_ids'],limit:50,context}},{json:{instance:'ocloud-staging',model:'product.product',domain:[['name','ilike',String(e.lines[0].description||'').slice(0,100)]],fields:['id','name','default_code','uom_id'],limit:50,context}},{json:{instance:'ocloud-staging',model:'account.tax',domain:[['company_id','=',1],['active','=',true]],fields:['id','name','amount','amount_type','type_tax_use'],limit:100,context}}];`,
    createCode: `
const p=input.payload; closed(p,['partner_id','currency_id','invoice_date','due_date','payment_term_id','vendor_reference','lines','evidence_refs','purchase_order_refs','receipt_refs','discrepancies','idempotency_key']);
for(const k of ['partner_id','currency_id']) must(Number.isInteger(p[k])&&p[k]>0,k); must(/^\\d{4}-\\d{2}-\\d{2}$/.test(p.invoice_date||''),'invoice_date'); must(p.due_date===null||/^\\d{4}-\\d{2}-\\d{2}$/.test(p.due_date),'due_date'); must(p.payment_term_id===null||(Number.isInteger(p.payment_term_id)&&p.payment_term_id>0),'payment_term_id'); must(typeof p.vendor_reference==='string'&&p.vendor_reference.length>=1&&p.vendor_reference.length<=100,'vendor_reference');
must(Array.isArray(p.lines)&&p.lines.length>=1&&p.lines.length<=200,'lines'); const commands=p.lines.map((line,i)=>{closed(line,['product_id','account_id','uom_id','description','quantity_milli','unit_price_minor','tax_ids']);for(const k of ['product_id','uom_id'])must(line[k]===null||(Number.isInteger(line[k])&&line[k]>0),'lines['+i+'].'+k);must(Number.isInteger(line.account_id)&&line.account_id>0,'lines['+i+'].account_id');must(typeof line.description==='string'&&line.description.length>=1&&line.description.length<=500,'lines['+i+'].description'); must(Number.isInteger(line.quantity_milli)&&line.quantity_milli>=1&&line.quantity_milli<=1000000,'lines['+i+'].quantity'); must(Number.isInteger(line.unit_price_minor)&&line.unit_price_minor>=0&&line.unit_price_minor<=1000000000,'lines['+i+'].price'); must(Array.isArray(line.tax_ids)&&line.tax_ids.length<=10&&line.tax_ids.length===new Set(line.tax_ids).size&&line.tax_ids.every(x=>Number.isInteger(x)&&x>0),'lines['+i+'].tax_ids'); const v={account_id:line.account_id,name:line.description,quantity:line.quantity_milli/1000,price_unit:line.unit_price_minor/100,tax_ids:[[6,0,line.tax_ids]]}; if(line.product_id!==null)v.product_id=line.product_id;if(line.uom_id!==null)v.product_uom_id=line.uom_id;return [0,0,v];});
texts(p.evidence_refs,1,20,512,true,'evidence_refs');texts(p.purchase_order_refs,0,20,100,true,'purchase_order_refs');texts(p.receipt_refs,0,20,100,true,'receipt_refs');texts(p.discrepancies,0,50,500,false,'discrepancies');must(p.idempotency_key===capabilityKey('vendor-bill',{capability:'prepare_vendor_bill_draft.v1',instance_id:'ocloud-staging',company_id:1,partner_id:p.partner_id,currency_id:p.currency_id,invoice_date:p.invoice_date,due_date:p.due_date,payment_term_id:p.payment_term_id,vendor_reference:p.vendor_reference,lines:p.lines,evidence_refs:p.evidence_refs,purchase_order_refs:p.purchase_order_refs,receipt_refs:p.receipt_refs,discrepancies:p.discrepancies}),'idempotency_key');
const values={move_type:'in_invoice',partner_id:p.partner_id,currency_id:p.currency_id,invoice_date:p.invoice_date,ref:p.vendor_reference,company_id:1,invoice_line_ids:commands};if(p.due_date!==null)values.invoice_date_due=p.due_date;if(p.payment_term_id!==null)values.invoice_payment_term_id=p.payment_term_id;return operation('account.move',values,{default_move_type:'in_invoice'});`,
    verify: `{instance:'ocloud-staging',model:'account.move',ids:[$json.id],fields:['id','company_id','state','move_type'],context:{allowed_company_ids:[1],force_company:1,default_move_type:'in_invoice'}}`,
    duplicate: `{instance:'ocloud-staging',model:'account.move',domain:[['company_id','=',1],['partner_id','=',$('Consume Approval').first().json.payload.partner_id],['currency_id','=',$('Consume Approval').first().json.payload.currency_id],['move_type','=','in_invoice'],['state','=','draft'],['ref','=',$('Consume Approval').first().json.payload.vendor_reference]],fields:['id','company_id','state','move_type'],limit:2,context:{allowed_company_ids:[1],force_company:1}}`,
    postcondition: `must(id(record.company_id)===1&&record.state==='draft'&&record.move_type==='in_invoice','vendor_bill_postcondition');`,
  },
  {
    slug: 'bank-statement-intake',
    name: 'Phase 8 - Bank Statement Intake v1',
    eventType: 'bank.statement_received.v1',
    actor: 'n8n-bank-statement',
    owner: 'Treasury Operations',
    reviewer: 'accounting_manager',
    capability: 'import_bank_transaction_draft.v1',
    profile: 'draft-operations',
    sourceCode: `const s=body.source;must(s?.account_map_ref==='secret://n8n/bank/account-map','account_map');must(typeof s?.source_id==='string'&&s.source_id.length>=3,'source_id');must(typeof s?.filename==='string'&&s.filename.length>=1&&s.filename.length<=255,'filename');must(['text/csv','application/vnd.ms-excel','application/pdf'].includes(s?.mime_type),'mime_type');must(Number.isInteger(s?.size_bytes)&&s.size_bytes>0&&s.size_bytes<=50000000,'size_bytes');must(body.statement?.journal_id===6,'journal_id');must(/^[0-9A-Za-z]{4}$/.test(body.statement?.account_last4||''),'account_last4');must(/^[A-Z]{3}$/.test(body.statement?.currency||''),'currency');must(/^\\d{4}-\\d{2}-\\d{2}$/.test(body.statement?.period_start||'')&&/^\\d{4}-\\d{2}-\\d{2}$/.test(body.statement?.period_end||'')&&body.statement.period_start<=body.statement.period_end,'period');`,
    extractValidation: `must(result.statement&&Number.isInteger(result.statement.journal_id),'statement');must(Array.isArray(result.lines)&&result.lines.length>=1,'normalized_lines');for(const line of result.lines){must(typeof line.external_transaction_id==='string'&&typeof line.normalized_description==='string'&&Number.isInteger(line.amount_minor)&&line.amount_minor!==0,'normalized_line');}`,
    reviewValidation: `must(Array.isArray(result.lines)&&result.lines.every(line=>['one_to_one','one_to_many','partial','unmatched'].includes(line.classification)&&typeof line.confidence==='number'&&Array.isArray(line.evidence_refs)&&Array.isArray(line.candidates)),'bank_match_classification');must(result.review?.state==='pending'&&result.review?.owner==='Treasury Operations'&&result.review?.reconciliation_confirmation_allowed===false,'review_state');`,
    readCode: `const e=$('Validate Extraction').first().json;const sample=e.lines[0];const context={allowed_company_ids:[1],force_company:1};return [{json:{instance:'ocloud-staging',model:'res.partner',domain:['|',['company_id','=',false],['company_id','=',1],['name','ilike',String(sample.normalized_description).slice(0,100)]],fields:['id','name','company_id'],limit:50,context}},{json:{instance:'ocloud-staging',model:'account.move',domain:[['company_id','=',1],['state','=','posted']],fields:['id','partner_id','amount_total','amount_residual','payment_state','ref','date'],limit:100,context}},{json:{instance:'ocloud-staging',model:'account.payment',domain:[['company_id','=',1]],fields:['id','partner_id','amount','date','state'],limit:100,context}}];`,
    createCode: `
const p=input.payload;closed(p,['journal_id','transaction_date','payment_reference','amount_minor','partner_id','foreign_currency_id','amount_currency_minor','external_transaction_id','evidence_refs','discrepancies','idempotency_key']);must(p.journal_id===6,'journal_id');must(/^\\d{4}-\\d{2}-\\d{2}$/.test(p.transaction_date||''),'transaction_date');must(typeof p.payment_reference==='string'&&p.payment_reference.length>=1&&p.payment_reference.length<=200,'payment_reference');must(Number.isInteger(p.amount_minor)&&p.amount_minor!==0&&Math.abs(p.amount_minor)<=100000000000000,'amount_minor');must(p.partner_id===null||(Number.isInteger(p.partner_id)&&p.partner_id>0),'partner_id');must((p.foreign_currency_id===null)===(p.amount_currency_minor===null),'foreign_currency_pair');if(p.foreign_currency_id!==null){must(Number.isInteger(p.foreign_currency_id)&&p.foreign_currency_id>0,'foreign_currency_id');must(Number.isInteger(p.amount_currency_minor)&&p.amount_currency_minor!==0&&Math.abs(p.amount_currency_minor)<=100000000000000,'amount_currency_minor');}must(typeof p.external_transaction_id==='string'&&p.external_transaction_id.length>=1&&p.external_transaction_id.length<=128,'external_transaction_id');texts(p.evidence_refs,1,20,512,true,'evidence_refs');texts(p.discrepancies,0,50,500,false,'discrepancies');must(p.idempotency_key===capabilityKey('bank-transaction',{capability:'import_bank_transaction_draft.v1',instance_id:'ocloud-staging',company_id:1,journal_id:p.journal_id,transaction_date:p.transaction_date,payment_reference:p.payment_reference,amount_minor:p.amount_minor,partner_id:p.partner_id,foreign_currency_id:p.foreign_currency_id,amount_currency_minor:p.amount_currency_minor,external_transaction_id:p.external_transaction_id,evidence_refs:p.evidence_refs,discrepancies:p.discrepancies}),'idempotency_key');const values={journal_id:p.journal_id,company_id:1,date:p.transaction_date,payment_ref:p.payment_reference,amount:p.amount_minor/100};if(p.partner_id!==null)values.partner_id=p.partner_id;if(p.foreign_currency_id!==null){values.foreign_currency_id=p.foreign_currency_id;values.amount_currency=p.amount_currency_minor/100;}return operation('account.bank.statement.line',values);`,
    verify: `{instance:'ocloud-staging',model:'account.bank.statement.line',ids:[$json.id],fields:['id','company_id','journal_id','state','is_reconciled'],context:{allowed_company_ids:[1],force_company:1}}`,
    duplicate: `{instance:'ocloud-staging',model:'account.bank.statement.line',domain:[['company_id','=',1],['journal_id','=',$('Consume Approval').first().json.payload.journal_id],['date','=',$('Consume Approval').first().json.payload.transaction_date],['amount','=',$('Consume Approval').first().json.payload.amount_minor/100],['payment_ref','=',$('Consume Approval').first().json.payload.payment_reference]],fields:['id','company_id','journal_id','state','is_reconciled'],limit:2,context:{allowed_company_ids:[1],force_company:1}}`,
    postcondition: `const expected=$('Consume Approval').first().json.payload.journal_id;must(id(record.company_id)===1&&id(record.journal_id)===expected&&record.state==='posted'&&record.is_reconciled===false,'bank_unreconciled_postcondition');`,
  },
  {
    slug: 'scheduled-business-briefs',
    name: 'Phase 8 - Scheduled Business Briefs v1',
    eventType: 'business.brief_scheduled.v1',
    actor: 'n8n-business-briefs',
    owner: 'Business Intelligence Operations',
    reviewer: 'finance_controller',
    capability: 'brief_delivery.v1',
    profile: 'reporting',
    schedule: true,
    sourceCode: `const now=new Date();const day=now.toISOString().slice(0,10);body={source:{schedule_id:'daily-management',definition_version:'v1',business_definition_ids:['outstanding-receivables.v1'],destination_ref:'destination://management-brief',allowlist_ref:'config://n8n/brief-destination-allowlist',schedule_approval_ref:'approval://brief-schedule/v1',timezone:'Asia/Jakarta',period_start:day+'T00:00:00+07:00',period_end:day+'T23:59:59+07:00',cutoff_at:now.toISOString()},artifact_ref:'schedule://daily-management/'+day,content_hash:'sha256:'+sha('daily-management:v1:'+day)};must(body.source.allowlist_ref==='config://n8n/brief-destination-allowlist','destination_allowlist');`,
    readCode: `const context={allowed_company_ids:[1],force_company:1};return [{json:{instance:'ocloud-staging',model:'account.move',domain:[['company_id','=',1],['state','=','posted'],['move_type','in',['out_invoice','in_invoice']]],fields:['id','move_type','amount_residual','currency_id','invoice_date_due'],limit:100,context}}];`,
    deliver: true,
  },
  {
    slug: 'indonesian-tax-working-papers',
    name: 'Phase 8 - Indonesian Tax Working Papers v1',
    eventType: 'id.tax_working_paper_requested.v1',
    actor: 'n8n-id-tax-working-paper',
    owner: 'Tax Operations',
    reviewer: 'tax_manager',
    capability: 'id_tax_working_paper_signoff.v1',
    profile: 'reporting',
    sourceCode: `must(/^\\d{4}-(0[1-9]|1[0-2])$/.test(body.request?.tax_period||''),'tax_period');must(typeof body.request?.rule_version==='string'&&body.request.rule_version.length>=3,'rule_version');must(typeof body.request?.rule_source_ref==='string'&&body.request.rule_source_ref.length>=3,'rule_source_ref');must(Array.isArray(body.request?.transaction_refs)&&body.request.transaction_refs.length>=1,'transaction_refs');must(Array.isArray(body.request?.document_refs),'document_refs');`,
    readCode: `const request=$('Validate Event').first().json.event.request;const [year,month]=request.tax_period.split('-').map(Number);const start=request.tax_period+'-01';const endMonth=month===12?1:month+1;const endYear=month===12?year+1:year;const end=String(endYear).padStart(4,'0')+'-'+String(endMonth).padStart(2,'0')+'-01';const context={allowed_company_ids:[1],force_company:1};return [{json:{instance:'ocloud-staging',model:'account.move',domain:[['company_id','=',1],['state','=','posted'],['date','>=',start],['date','<',end]],fields:['id','date','move_type','amount_untaxed','amount_tax','currency_id','partner_id','ref'],limit:100,context}}];`,
    signoff: true,
  },
];

function sha(value) { return createHash('sha256').update(value).digest('hex'); }
function uuid(seed) {
  const h = sha(seed).slice(0, 32).split('');
  h[12] = '4'; h[16] = ((parseInt(h[16], 16) & 3) | 8).toString(16);
  return `${h.slice(0,8).join('')}-${h.slice(8,12).join('')}-${h.slice(12,16).join('')}-${h.slice(16,20).join('')}-${h.slice(20).join('')}`;
}
function node(spec, name, type, typeVersion, x, y, parameters, extra = {}) {
  return { id: uuid(`${spec.slug}:${name}`), name, type, typeVersion, position: [x, y], parameters, ...extra };
}
function connect(connections, from, to, output = 0) {
  const main = connections[from]?.main || [];
  while (main.length <= output) main.push([]);
  main[output].push({ node: to, type: 'main', index: 0 });
  connections[from] = { main };
}
const pgCred = { postgres: { id: 'phase8-state-postgres', name: 'phase8-state-postgres' } };
const hookCred = { httpHeaderAuth: { id: 'phase8-webhook-header', name: 'phase8-webhook-header' } };
const mcpCred = { httpBearerAuth: { id: 'odoo-mcp-staging-bearer', name: 'odoo-mcp-staging-bearer' } };
const alertCred = { httpHeaderAuth: { id: 'phase8-alert-webhook', name: 'phase8-alert-webhook' } };
const extractorCred = { httpHeaderAuth: { id: 'phase8-extractor-header', name: 'phase8-extractor-header' } };
const deliveryCred = { httpHeaderAuth: { id: 'phase8-delivery-header', name: 'phase8-delivery-header' } };
const taxRulesCred = { httpHeaderAuth: { id: 'phase8-tax-rules-header', name: 'phase8-tax-rules-header' } };

const validationCode = (s) => `
const crypto=require('crypto'); const sha=v=>crypto.createHash('sha256').update(v).digest('hex'); const must=(ok,code)=>{if(!ok)throw new Error('permanent:'+code)};
let body=${s.schedule ? '{}' : "$input.first().json.body ?? $input.first().json"};let reason_code=null;try{${s.sourceCode}must(body&&typeof body==='object'&&!Array.isArray(body),'body');must(typeof body.artifact_ref==='string'&&body.artifact_ref.length>=3&&body.artifact_ref.length<=512,'artifact_ref');must(/^sha256:[0-9a-f]{64}$/.test(body.content_hash||''),'content_hash');}catch(error){reason_code=String(error.message||error).replace(/^permanent:/,'').slice(0,100);}
const raw=JSON.stringify(body??{});const valid=reason_code===null;const content_hash=/^sha256:[0-9a-f]{64}$/.test(body?.content_hash||'')?body.content_hash:'sha256:'+sha(raw);const artifact_ref=typeof body?.artifact_ref==='string'&&body.artifact_ref.length>=3&&body.artifact_ref.length<=512?body.artifact_ref:'rejected://${s.actor}/'+sha(raw).slice(0,32);
const correlation_id=crypto.randomUUID(); const idempotency_key='${s.slug}:v1:'+sha('${s.eventType}|ocloud-staging|1|'+artifact_ref+'|'+content_hash);
return [{json:{valid,reason_code,event:body,event_type:'${s.eventType}',schema_version:'1.0',correlation_id,idempotency_key,content_hash,artifact_ref,owner:'${s.owner}',actor:'${s.actor}',context:{instance_id:'ocloud-staging',company_id:1,profile_id:'${s.profile}'}}}];`;

const reviewCode = (s) => `
const crypto=require('crypto');const must=(ok,code)=>{if(!ok)throw new Error('permanent:'+code)};const base=$('Validate Event').first().json;const result=$input.first().json;if(result.error_class==='permanent')throw new Error('permanent:'+result.reason_code);${s.reviewValidation}const payload=result.capability_payload;if(!payload||typeof payload!=='object'||Array.isArray(payload))throw new Error('permanent:missing_review_payload');const payload_hash='sha256:'+crypto.createHash('sha256').update(JSON.stringify(payload)).digest('hex');return [{json:{...base,approval_id:crypto.randomUUID(),capability:'${s.capability}',reviewer_role:'${s.reviewer}',payload_hash,payload,expires_at:new Date(Date.now()+15*60*1000).toISOString()}}];`;

const extractionCode = s => `const result=$input.first().json;const must=(ok,code)=>{if(!ok)throw new Error('permanent:'+code)};if(result.error_class==='permanent')throw new Error('permanent:'+result.reason_code);${s.extractValidation}return [{json:result}];`;

const boundedCode = (s) => `
const crypto=require('crypto');const input=$input.first().json; const must=(ok,code)=>{if(!ok)throw new Error('permanent:'+code)}; const closed=(v,keys)=>{must(v&&typeof v==='object'&&!Array.isArray(v),'payload');const extra=Object.keys(v).filter(k=>!keys.includes(k));must(extra.length===0,'unknown_'+extra[0]);};const stable=v=>Array.isArray(v)?'['+v.map(stable).join(',')+']':v&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+stable(v[k])).join(',')+'}':JSON.stringify(v);const capabilityKey=(prefix,value)=>prefix+':v1:'+crypto.createHash('sha256').update(stable(value)).digest('hex');const texts=(values,min,max,length,unique,name)=>must(Array.isArray(values)&&values.length>=min&&values.length<=max&&values.every(v=>typeof v==='string'&&v.length>=1&&v.length<=length)&&(!unique||values.length===new Set(values).size),name); const operation=(model,values,more={})=>[{json:{instance:'ocloud-staging',model,values,context:{allowed_company_ids:[1],force_company:1,...more}}}]; ${s.createCode}`;

const decodeMcpCode = `const decode=raw=>{let value=raw.structuredContent??raw.content?.find(x=>x.type==='text')?.text??raw;for(let i=0;i<4;i++){if(typeof value==='string'){value=JSON.parse(value);continue;}if(value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).length===1&&Object.hasOwn(value,'result')){value=value.result;continue;}break;}if(!value||typeof value!=='object'||Array.isArray(value)||value.error)throw new Error('invalid_mcp_result');return value};return $input.all().map((item,index)=>({json:decode(item.json),pairedItem:{item:index}}));`;

const postconditionCode = s => `const must=(ok,code)=>{if(!ok)throw new Error(code)};const id=v=>Array.isArray(v)?v[0]:v;const created=$('Decode Created Record').first().json;const result=$input.first().json;const records=result.records??result;const record=Array.isArray(records)?records[0]:records;if(!record||record.id!==created.id)throw new Error('record_verification_missing');${s.postcondition}return [{json:{id:created.id,record}}];`;

function workflow(spec) {
  const nodes = [], connections = {};
  const add = (...args) => nodes.push(node(spec, ...args));
  const retry = (name, type, version, x, y, parameters, extra, success, failure) => {
    const attempts = [name, `${name} Attempt 2`, `${name} Attempt 3`, `${name} Attempt 4`];
    const waits = [[`${name} Backoff 2s`, 2], [`${name} Backoff 10s`, 10], [`${name} Backoff 30s`, 30]];
    const classifyCode = `const value=$input.first().json;const error=value.error??value;const message=String(error.message??error.description??'');const match=message.match(/\\b(?:HTTP|status(?: code)?)\\D*(\\d{3})\\b/i);const status=Number(error.httpCode??error.statusCode??error.status??value.httpCode??value.statusCode??match?.[1]);const permanent=Number.isFinite(status)?status>=400&&status<500&&![408,425,429].includes(status):/(denied|forbidden|unauthori[sz]ed|access|schema|company)/i.test(message);return [{json:{...value,retryable:!permanent}}];`;
    attempts.forEach((attempt, index) => add(attempt, type, version, x + index * 240, y, parameters, { ...extra, onError: 'continueErrorOutput' }));
    waits.forEach(([wait, amount], index) => {
      const classify = `${name} Classify Error ${index + 1}`;
      const retryable = `${name} Retryable ${index + 1}?`;
      add(classify, 'n8n-nodes-base.code', 2, x + index * 240 + 60, y + 120, { mode: 'runOnceForAllItems', jsCode: classifyCode });
      add(retryable, 'n8n-nodes-base.if', 2.3, x + index * 240 + 90, y + 160, { conditions: { options: { version: 2, leftValue: '', caseSensitive: true, typeValidation: 'strict' }, combinator: 'and', conditions: [{ id: uuid(`${spec.slug}:${retryable}`), leftValue: '={{ $json.retryable }}', rightValue: true, operator: { type: 'boolean', operation: 'true', singleValue: true } }] }, options: {} });
      add(wait, 'n8n-nodes-base.wait', 1.1, x + index * 240 + 120, y + 160, { resume: 'timeInterval', amount, unit: 'seconds', options: {} });
      connect(connections, attempts[index], classify, 1);
      connect(connections, classify, retryable);
      connect(connections, retryable, wait, 0);
      connect(connections, retryable, failure, 1);
      connect(connections, wait, attempts[index + 1]);
    });
    attempts.forEach(attempt => connect(connections, attempt, success, 0));
    const finalClassify = `${name} Classify Error 4`;
    add(finalClassify, 'n8n-nodes-base.code', 2, x + 780, y + 120, { mode: 'runOnceForAllItems', jsCode: classifyCode });
    connect(connections, attempts.at(-1), finalClassify, 1);
    connect(connections, finalClassify, failure);
  };
  if (spec.schedule) {
    add('Trigger', 'n8n-nodes-base.scheduleTrigger', 1.2, 0, 0, { rule: { interval: [{ field: 'cronExpression', expression: '0 7 * * 1-5' }] } });
    add('Replay Trigger', 'n8n-nodes-base.webhook', 2.1, 0, 120, { httpMethod: 'POST', path: `phase8/${spec.slug}/v1/replay`, authentication: 'headerAuth', responseMode: 'lastNode', options: {} }, { webhookId: uuid(`${spec.slug}:replay`), credentials: hookCred });
  }
  else add('Trigger', 'n8n-nodes-base.webhook', 2.1, 0, 0, { httpMethod: 'POST', path: `phase8/${spec.slug}/v1`, authentication: 'headerAuth', responseMode: 'responseNode', options: {} }, { webhookId: uuid(`${spec.slug}:trigger`), credentials: hookCred });
  add('Validate Event', 'n8n-nodes-base.code', 2, 240, 0, { mode: 'runOnceForAllItems', jsCode: validationCode(spec) });
  add('Claim Event', 'n8n-nodes-base.postgres', 2.6, 480, 0, { operation: 'executeQuery', query: "WITH claimed AS (INSERT INTO phase8.events(idempotency_key,workflow,schema_version,correlation_id,content_hash,artifact_ref,status,owner) VALUES ($1,$2,$3,$4,$5,$6,CASE WHEN $8 THEN 'received' ELSE 'exception' END,$7) ON CONFLICT DO NOTHING RETURNING 1) SELECT EXISTS(SELECT 1 FROM claimed) AS claimed", options: { queryReplacement: "={{ [$json.idempotency_key, $json.event_type, $json.schema_version, $json.correlation_id, $json.content_hash, $json.artifact_ref, $json.owner, $json.valid] }}" } }, { credentials: pgCred });
  add('Is New', 'n8n-nodes-base.if', 2.3, 720, 0, { conditions: { options: { version: 2, leftValue: '', caseSensitive: true, typeValidation: 'strict' }, combinator: 'and', conditions: [{ id: uuid(`${spec.slug}:claimed`), leftValue: '={{ $json.claimed }}', rightValue: true, operator: { type: 'boolean', operation: 'true', singleValue: true } }] }, options: {} });
  add('Valid?', 'n8n-nodes-base.if', 2.3, 960, -80, { conditions: { options: { version: 2, leftValue: '', caseSensitive: true, typeValidation: 'strict' }, combinator: 'and', conditions: [{ id: uuid(`${spec.slug}:valid`), leftValue: '={{ $("Validate Event").first().json.valid }}', rightValue: true, operator: { type: 'boolean', operation: 'true', singleValue: true } }] }, options: {} });
  const extracts = !spec.schedule && !spec.signoff;
  if (extracts) {
    retry('Extract Source', 'n8n-nodes-base.httpRequest', 4.4, 1200, -160, { method: 'POST', url: `={{ $env.PHASE8_EXTRACTOR_URL }}/${spec.slug}/extract/v1`, authentication: 'genericCredentialType', genericAuthType: 'httpHeaderAuth', sendBody: true, contentType: 'raw', rawContentType: 'application/json', body: '={{ JSON.stringify($("Validate Event").first().json.event) }}', options: { timeout: 30000 } }, { credentials: extractorCred }, 'Validate Extraction', 'Queue Exception');
    add('Validate Extraction', 'n8n-nodes-base.code', 2, 2160, -160, { mode: 'runOnceForAllItems', jsCode: extractionCode(spec) }, { onError: 'continueErrorOutput' });
  }
  add('Prepare Odoo Reads', 'n8n-nodes-base.code', 2, 2400, -160, { mode: 'runOnceForAllItems', jsCode: spec.readCode }, { onError: 'continueErrorOutput' });
  retry('Read Odoo', '@n8n/n8n-nodes-langchain.mcpClient', 1.1, 2640, -160, { serverTransport: 'httpStreamable', endpointUrl: '={{ $env.ODOO_MCP_STAGING_URL }}', authentication: 'bearerAuth', tool: { mode: 'id', value: 'odoo_search_read' }, inputMode: 'json', jsonInput: '={{ JSON.stringify($json) }}', options: { timeout: 30000, convertToBinary: false } }, { credentials: mcpCred }, 'Decode Odoo Read', 'Queue Exception');
  add('Decode Odoo Read', 'n8n-nodes-base.code', 2, 3600, -160, { mode: 'runOnceForAllItems', jsCode: decodeMcpCode }, { onError: 'continueErrorOutput' });
  add('Aggregate Odoo Reads', 'n8n-nodes-base.code', 2, 3720, -160, { mode: 'runOnceForAllItems', jsCode: 'return [{json:{results:$input.all().map(item=>item.json)}}];' }, { onError: 'continueErrorOutput' });
  if (extracts) retry('Match and Prepare Review', 'n8n-nodes-base.httpRequest', 4.4, 3840, -160, { method: 'POST', url: `={{ $env.PHASE8_EXTRACTOR_URL }}/${spec.slug}/match/v1`, authentication: 'genericCredentialType', genericAuthType: 'httpHeaderAuth', sendBody: true, contentType: 'raw', rawContentType: 'application/json', body: '={{ JSON.stringify({event: $("Validate Event").first().json.event, extraction: $("Validate Extraction").first().json, odoo: $json.results}) }}', options: { timeout: 30000 } }, { credentials: extractorCred }, 'Build Review', 'Queue Exception');
  if (spec.signoff) retry('Calculate Tax Working Paper', 'n8n-nodes-base.httpRequest', 4.4, 3840, -160, { method: 'POST', url: '={{ $env.PHASE8_TAX_RULES_URL }}', authentication: 'genericCredentialType', genericAuthType: 'httpHeaderAuth', sendBody: true, contentType: 'raw', rawContentType: 'application/json', body: '={{ JSON.stringify({request: $("Validate Event").first().json.event.request, odoo: $json.results}) }}', options: { timeout: 30000 } }, { credentials: taxRulesCred }, 'Build Review', 'Queue Exception');
  if (spec.schedule) add('Build Review', 'n8n-nodes-base.code', 2, 3840, -160, { mode: 'runOnceForAllItems', jsCode: `const base=$('Validate Event').first().json;const source=base.event.source;const rows=$input.first().json.results;const payload={schedule_id:source.schedule_id,definition_version:source.definition_version,business_definition_ids:source.business_definition_ids,destination_ref:source.destination_ref,allowlist_ref:source.allowlist_ref,schedule_approval_ref:source.schedule_approval_ref,timezone:source.timezone,period_start:source.period_start,period_end:source.period_end,cutoff_at:source.cutoff_at,data_fresh_at:new Date().toISOString(),partial_failure:false,failures:[],currency:'IDR',included_states:['posted'],rows};return [{json:{...base,capability:'brief_delivery.v1',payload_hash:base.content_hash,payload,approval_id:require('crypto').randomUUID(),reviewer_role:'finance_controller',expires_at:new Date(Date.now()+15*60*1000).toISOString()}}];` }, { onError: 'continueErrorOutput' });
  else if (spec.signoff) add('Build Review', 'n8n-nodes-base.code', 2, 4800, -160, { mode: 'runOnceForAllItems', jsCode: `const crypto=require('crypto');const must=(ok,code)=>{if(!ok)throw new Error('permanent:'+code)};const base=$('Validate Event').first().json;const result=$input.first().json;must(result.rule_version===base.event.request.rule_version,'tax_rule_version');must(Array.isArray(result.calculation)&&result.calculation.length>=1,'tax_calculation');must(result.calculation.every(x=>typeof x.tax_object==='string'&&Number.isInteger(x.dpp_minor)&&Number.isInteger(x.rate_basis_points)&&Number.isInteger(x.tax_minor)&&typeof x.responsibility==='string'&&Array.isArray(x.evidence_refs)&&Array.isArray(x.assumptions)),'tax_calculation_fields');must(result.reconciliation&&Number.isInteger(result.reconciliation.odoo_total_minor)&&Number.isInteger(result.reconciliation.working_paper_total_minor)&&Number.isInteger(result.reconciliation.difference_minor)&&Array.isArray(result.reconciliation.missing_documents)&&Array.isArray(result.reconciliation.exceptions),'tax_reconciliation');const payload={request:base.event.request,calculation:result.calculation,reconciliation:result.reconciliation,review:{state:'pending',owner:'Tax Operations',reviewer_id:null,signoff_at:null,statutory_submission_allowed:false}};return [{json:{...base,capability:'id_tax_working_paper_signoff.v1',payload_hash:'sha256:'+crypto.createHash('sha256').update(JSON.stringify(payload)).digest('hex'),payload,approval_id:crypto.randomUUID(),reviewer_role:'tax_manager',expires_at:new Date(Date.now()+15*60*1000).toISOString()}}];` }, { onError: 'continueErrorOutput' });
  else add('Build Review', 'n8n-nodes-base.code', 2, 4800, -160, { mode: 'runOnceForAllItems', jsCode: reviewCode(spec) }, { onError: 'continueErrorOutput' });
  const reviewQuery = spec.schedule
    ? "WITH approval AS (INSERT INTO phase8.approvals(approval_id,idempotency_key,capability,payload_hash,payload,reviewer_role,reviewer_id,state,expires_at,consumed_at) VALUES ($1,$2,$3,$4,$5::jsonb,$6,$8,'consumed',$7,now()) ON CONFLICT (idempotency_key,payload_hash) DO UPDATE SET state='consumed',reviewer_id=EXCLUDED.reviewer_id,consumed_at=now() RETURNING approval_id,state,expires_at) UPDATE phase8.events SET status='approved',updated_at=now() WHERE idempotency_key=$2 RETURNING (SELECT approval_id FROM approval) approval_id,(SELECT state FROM approval) review_state,(SELECT expires_at FROM approval) expires_at"
    : "WITH approval AS (INSERT INTO phase8.approvals(approval_id,idempotency_key,capability,payload_hash,payload,reviewer_role,state,expires_at) VALUES ($1,$2,$3,$4,$5::jsonb,$6,'pending',$7) ON CONFLICT (idempotency_key,payload_hash) DO UPDATE SET expires_at=GREATEST(phase8.approvals.expires_at,EXCLUDED.expires_at) RETURNING approval_id,state,expires_at) UPDATE phase8.events SET status='review_pending',updated_at=now() WHERE idempotency_key=$2 RETURNING (SELECT approval_id FROM approval) approval_id,(SELECT state FROM approval) review_state,(SELECT expires_at FROM approval) expires_at";
  add('Queue Review', 'n8n-nodes-base.postgres', 2.6, 1680, -80, { operation: 'executeQuery', query: reviewQuery, options: { queryReplacement: spec.schedule ? "={{ [$json.approval_id,$json.idempotency_key,$json.capability,$json.payload_hash,$json.payload,$json.reviewer_role,$json.expires_at,$json.payload.schedule_approval_ref] }}" : "={{ [$json.approval_id,$json.idempotency_key,$json.capability,$json.payload_hash,$json.payload,$json.reviewer_role,$json.expires_at] }}" } }, { credentials: pgCred });
  if (spec.schedule) {
    retry('Deliver Brief', 'n8n-nodes-base.httpRequest', 4.4, 1920, -80, { method: 'POST', url: '={{ $env.PHASE8_BRIEF_DELIVERY_URL }}', authentication: 'genericCredentialType', genericAuthType: 'httpHeaderAuth', sendBody: true, contentType: 'raw', rawContentType: 'application/json', body: '={{ JSON.stringify($("Build Review").first().json.payload) }}', options: { timeout: 30000 } }, { credentials: deliveryCred }, 'Complete', 'Queue Exception');
    add('Complete', 'n8n-nodes-base.postgres', 2.6, 2160, -80, { operation: 'executeQuery', query: "UPDATE phase8.events SET status='completed',updated_at=now() WHERE idempotency_key=$1 RETURNING idempotency_key,status", options: { queryReplacement: '={{ [$("Validate Event").first().json.idempotency_key] }}' } }, { credentials: pgCred });
  }
  if (!spec.schedule) add('Accepted', 'n8n-nodes-base.respondToWebhook', 1.4, 1920, -80, { respondWith: 'json', responseBody: '={{ {status:"review_pending", approval_id:$json.approval_id, expires_at:$json.expires_at} }}', options: { responseCode: 202 } });
  if (spec.schedule) add('Duplicate', 'n8n-nodes-base.noOp', 1, 960, 160, {});
  else add('Duplicate', 'n8n-nodes-base.respondToWebhook', 1.4, 960, 160, { respondWith: 'json', responseBody: '={{ {status:"duplicate", idempotency_key:$("Validate Event").first().json.idempotency_key} }}', options: { responseCode: 200 } });
  add('Queue Exception', 'n8n-nodes-base.postgres', 2.6, 1440, 240, { operation: 'executeQuery', query: "WITH e AS (SELECT idempotency_key,correlation_id,owner FROM phase8.events WHERE idempotency_key=$1), ins AS (INSERT INTO phase8.exceptions(exception_id,idempotency_key,error_class,reason_code,owner) SELECT md5($1 || ':' || $3)::uuid,e.idempotency_key,$2,$3,e.owner FROM e ON CONFLICT (exception_id) DO NOTHING RETURNING exception_id) UPDATE phase8.events SET status='exception',updated_at=now() WHERE idempotency_key=$1 RETURNING COALESCE((SELECT exception_id FROM ins),md5($1 || ':' || $3)::uuid) exception_id,status", options: { queryReplacement: "={{ [$(\"Validate Event\").first().json.idempotency_key, $json.retryable === false ? 'permanent' : 'retryable', $json.retryable === false ? 'external_permanent_failure' : 'external_retry_exhausted'] }}" } }, { credentials: pgCred });
  add('Queue Permanent Exception', 'n8n-nodes-base.postgres', 2.6, 1200, 240, { operation: 'executeQuery', query: "WITH e AS (SELECT idempotency_key,owner FROM phase8.events WHERE idempotency_key=$1), ins AS (INSERT INTO phase8.exceptions(exception_id,idempotency_key,error_class,reason_code,owner) SELECT md5($1 || ':' || $2)::uuid,e.idempotency_key,'permanent',$2,e.owner FROM e ON CONFLICT (exception_id) DO NOTHING RETURNING exception_id) UPDATE phase8.events SET status='exception',updated_at=now() WHERE idempotency_key=$1 RETURNING COALESCE((SELECT exception_id FROM ins),md5($1 || ':' || $2)::uuid) exception_id,status", options: { queryReplacement: "={{ [$(\"Validate Event\").first().json.idempotency_key, $(\"Validate Event\").first().json.reason_code ?? 'processing_validation_failed'] }}" } }, { credentials: pgCred });
  retry('Alert Owner', 'n8n-nodes-base.httpRequest', 4.4, 1680, 240, { method: 'POST', url: '={{ $env.PHASE8_ALERT_URL }}', authentication: 'genericCredentialType', genericAuthType: 'httpHeaderAuth', sendBody: true, contentType: 'raw', rawContentType: 'application/json', body: `={{ JSON.stringify({workflow:'${spec.slug}',owner:'${spec.owner}',status:$json.status,exception_id:$json.exception_id,correlation_id:$("Validate Event").first().json.correlation_id,idempotency_key:$("Validate Event").first().json.idempotency_key}) }}`, options: { timeout: 10000 } }, { credentials: alertCred }, 'Alert End', 'Alert End');
  add('Alert End', 'n8n-nodes-base.noOp', 1, 2640, 240, {});
  if (!spec.schedule) add('Exception Response', 'n8n-nodes-base.respondToWebhook', 1.4, 1680, 240, { respondWith: 'json', responseBody: '={{ {status:$json.status, exception_id:$json.exception_id} }}', options: { responseCode: 503 } });
  if (!spec.schedule) add('Permanent Response', 'n8n-nodes-base.respondToWebhook', 1.4, 1440, 360, { respondWith: 'json', responseBody: '={{ {status:"exception", exception_id:$json.exception_id} }}', options: { responseCode: 422 } });

  connect(connections, 'Trigger', 'Validate Event'); if (spec.schedule) connect(connections, 'Replay Trigger', 'Validate Event'); connect(connections, 'Validate Event', 'Claim Event'); connect(connections, 'Claim Event', 'Is New'); connect(connections, 'Is New', 'Valid?', 0); connect(connections, 'Is New', 'Duplicate', 1); connect(connections, 'Valid?', extracts ? 'Extract Source' : 'Prepare Odoo Reads', 0); connect(connections, 'Valid?', 'Queue Permanent Exception', 1);
  if (extracts) { connect(connections, 'Validate Extraction', 'Prepare Odoo Reads', 0); connect(connections, 'Validate Extraction', 'Queue Permanent Exception', 1); }
  connect(connections, 'Prepare Odoo Reads', 'Read Odoo', 0); connect(connections, 'Prepare Odoo Reads', 'Queue Permanent Exception', 1);
  connect(connections, 'Decode Odoo Read', 'Aggregate Odoo Reads', 0); connect(connections, 'Decode Odoo Read', 'Queue Permanent Exception', 1); connect(connections, 'Aggregate Odoo Reads', extracts ? 'Match and Prepare Review' : spec.signoff ? 'Calculate Tax Working Paper' : 'Build Review', 0); connect(connections, 'Aggregate Odoo Reads', 'Queue Permanent Exception', 1);
  connect(connections, 'Build Review', 'Queue Review', 0); connect(connections, 'Build Review', 'Queue Permanent Exception', 1);
  connect(connections, 'Queue Exception', 'Alert Owner'); connect(connections, 'Queue Permanent Exception', 'Alert Owner');
  if (spec.schedule) connect(connections, 'Queue Review', 'Deliver Brief');
  else { connect(connections, 'Queue Review', 'Accepted'); connect(connections, 'Queue Exception', 'Exception Response'); connect(connections, 'Queue Permanent Exception', 'Permanent Response'); }

  if (!spec.schedule) {
    add('Approval Trigger', 'n8n-nodes-base.webhook', 2.1, 0, 520, { httpMethod: 'POST', path: `phase8/${spec.slug}/v1/approval`, authentication: 'headerAuth', responseMode: 'responseNode', options: {} }, { webhookId: uuid(`${spec.slug}:approval`), credentials: hookCred });
    add('Validate Approval', 'n8n-nodes-base.code', 2, 240, 520, { mode: 'runOnceForAllItems', jsCode: `const b=$input.first().json.body??$input.first().json;const must=(x,c)=>{if(!x)throw new Error('permanent:'+c)};must(/^[0-9a-f-]{36}$/.test(b.approval_id||''),'approval_id');must(['approved','rejected'].includes(b.decision),'decision');must(typeof b.reviewer_id==='string'&&b.reviewer_id.length>=1&&b.reviewer_id.length<=100,'reviewer_id');must(/^sha256:[0-9a-f]{64}$/.test(b.payload_hash||''),'payload_hash');return [{json:{...b,reviewer_role:'${spec.reviewer}'}}];` });
    add('Consume Approval', 'n8n-nodes-base.postgres', 2.6, 480, 520, { operation: 'executeQuery', query: "WITH decided AS (UPDATE phase8.approvals SET state=CASE WHEN $2='approved' THEN 'consumed' ELSE 'rejected' END,reviewer_id=$3,consumed_at=CASE WHEN $2='approved' THEN now() ELSE NULL END WHERE approval_id=$1 AND state='pending' AND expires_at>now() AND payload_hash=$4 AND reviewer_role=$5 RETURNING approval_id,idempotency_key,capability,payload_hash,payload,reviewer_id,state), event AS (UPDATE phase8.events e SET status=CASE WHEN d.state='consumed' THEN 'approved' ELSE 'rejected' END,updated_at=now() FROM decided d WHERE e.idempotency_key=d.idempotency_key RETURNING e.idempotency_key) SELECT d.*,d.state='consumed' AS approved FROM decided d JOIN event e USING(idempotency_key)", options: { queryReplacement: "={{ [$json.approval_id,$json.decision,$json.reviewer_id,$json.payload_hash,$json.reviewer_role] }}" } }, { credentials: pgCred, alwaysOutputData: true });
    add('Approved?', 'n8n-nodes-base.if', 2.3, 720, 520, { conditions: { options: { version: 2, leftValue: '', caseSensitive: true, typeValidation: 'strict' }, combinator: 'and', conditions: [{ id: uuid(`${spec.slug}:approved`), leftValue: '={{ $json.approved }}', rightValue: true, operator: { type: 'boolean', operation: 'true', singleValue: true } }] }, options: {} });
    if (spec.signoff) {
      add('Complete', 'n8n-nodes-base.postgres', 2.6, 960, 440, { operation: 'executeQuery', query: "WITH paper AS (UPDATE phase8.approvals SET payload=jsonb_set(payload,'{review}',jsonb_build_object('state','signed_off','owner','Tax Operations','reviewer_id',$3,'signoff_at',now(),'statutory_submission_allowed',false)) WHERE approval_id=$2 RETURNING payload) UPDATE phase8.events SET status='completed',updated_at=now() WHERE idempotency_key=$1 RETURNING idempotency_key,status,(SELECT payload FROM paper) working_paper", options: { queryReplacement: '={{ [$json.idempotency_key,$json.approval_id,$json.reviewer_id] }}' } }, { credentials: pgCred });
    } else {
      add('Build Bounded Operation', 'n8n-nodes-base.code', 2, 960, 440, { mode: 'runOnceForAllItems', jsCode: boundedCode(spec) });
      add('Prepare Duplicate Check', 'n8n-nodes-base.code', 2, 1200, 440, { mode: 'runOnceForAllItems', jsCode: `return [{json:${spec.duplicate}}];` }, { onError: 'continueErrorOutput' });
      retry('Check Existing Odoo', '@n8n/n8n-nodes-langchain.mcpClient', 1.1, 1440, 440, { serverTransport: 'httpStreamable', endpointUrl: '={{ $env.ODOO_MCP_STAGING_URL }}', authentication: 'bearerAuth', tool: { mode: 'id', value: 'odoo_search_read' }, inputMode: 'json', jsonInput: '={{ JSON.stringify($json) }}', options: { timeout: 30000, convertToBinary: false } }, { credentials: mcpCred }, 'Decode Duplicate Check', 'Queue Approval Exception');
      add('Decode Duplicate Check', 'n8n-nodes-base.code', 2, 1440, 440, { mode: 'runOnceForAllItems', jsCode: decodeMcpCode }, { onError: 'continueErrorOutput' });
      add('Classify Duplicate', 'n8n-nodes-base.code', 2, 1680, 440, { mode: 'runOnceForAllItems', jsCode: `const records=$input.first().json.records??[];if(!Array.isArray(records))throw new Error('invalid_duplicate_result');if(records.length>1)throw new Error('multiple_duplicate_candidates');return [{json:{exists:records.length===1,record:records[0]??null}}];` }, { onError: 'continueErrorOutput' });
      add('No Existing?', 'n8n-nodes-base.if', 2.3, 1920, 440, { conditions: { options: { version: 2, leftValue: '', caseSensitive: true, typeValidation: 'strict' }, combinator: 'and', conditions: [{ id: uuid(`${spec.slug}:no-existing`), leftValue: '={{ $json.exists }}', rightValue: false, operator: { type: 'boolean', operation: 'false', singleValue: true } }] }, options: {} });
      add('Create Odoo Record', '@n8n/n8n-nodes-langchain.mcpClient', 1.1, 2160, 360, { serverTransport: 'httpStreamable', endpointUrl: '={{ $env.ODOO_MCP_STAGING_URL }}', authentication: 'bearerAuth', tool: { mode: 'id', value: 'odoo_create' }, inputMode: 'json', jsonInput: '={{ JSON.stringify($("Build Bounded Operation").first().json) }}', options: { timeout: 30000, convertToBinary: false } }, { credentials: mcpCred, onError: 'continueErrorOutput' });
      add('Decode Created Record', 'n8n-nodes-base.code', 2, 2400, 360, { mode: 'runOnceForAllItems', jsCode: decodeMcpCode }, { onError: 'continueErrorOutput' });
      add('Prepare Verification', 'n8n-nodes-base.code', 2, 2640, 360, { mode: 'runOnceForAllItems', jsCode: `return [{json:${spec.verify}}];` }, { onError: 'continueErrorOutput' });
      add('Verify Odoo Record', '@n8n/n8n-nodes-langchain.mcpClient', 1.1, 2880, 360, { serverTransport: 'httpStreamable', endpointUrl: '={{ $env.ODOO_MCP_STAGING_URL }}', authentication: 'bearerAuth', tool: { mode: 'id', value: 'odoo_read' }, inputMode: 'json', jsonInput: '={{ JSON.stringify($json) }}', options: { timeout: 30000, convertToBinary: false } }, { credentials: mcpCred, onError: 'continueErrorOutput' });
      add('Decode Verification', 'n8n-nodes-base.code', 2, 2880, 360, { mode: 'runOnceForAllItems', jsCode: decodeMcpCode }, { onError: 'continueErrorOutput' });
      add('Verify Postcondition', 'n8n-nodes-base.code', 2, 3120, 360, { mode: 'runOnceForAllItems', jsCode: postconditionCode(spec) }, { onError: 'continueErrorOutput' });
      add('Complete', 'n8n-nodes-base.postgres', 2.6, 3360, 360, { operation: 'executeQuery', query: "UPDATE phase8.events SET status='completed',odoo_model=$2,odoo_record_id=$3,updated_at=now() WHERE idempotency_key=$1 RETURNING idempotency_key,status,odoo_model,odoo_record_id", options: { queryReplacement: `={{ [$("Consume Approval").first().json.idempotency_key, $("Build Bounded Operation").first().json.model, $("Decode Created Record").first().json.id] }}` } }, { credentials: pgCred });
      add('Complete Duplicate', 'n8n-nodes-base.postgres', 2.6, 2160, 560, { operation: 'executeQuery', query: "UPDATE phase8.events SET status='duplicate',odoo_model=$2,odoo_record_id=$3,updated_at=now() WHERE idempotency_key=$1 RETURNING idempotency_key,status,odoo_model,odoo_record_id", options: { queryReplacement: `={{ [$("Consume Approval").first().json.idempotency_key, $("Build Bounded Operation").first().json.model, $("Classify Duplicate").first().json.record.id] }}` } }, { credentials: pgCred });
      add('Queue Approval Exception', 'n8n-nodes-base.postgres', 2.6, 1920, 760, { operation: 'executeQuery', query: "WITH ins AS (INSERT INTO phase8.exceptions(exception_id,idempotency_key,error_class,reason_code,owner) SELECT md5($1 || ':approval_prewrite_failed')::uuid,$1,'permanent','approval_prewrite_failed',owner FROM phase8.events WHERE idempotency_key=$1 ON CONFLICT (exception_id) DO NOTHING RETURNING exception_id) UPDATE phase8.events SET status='exception',updated_at=now() WHERE idempotency_key=$1 RETURNING COALESCE((SELECT exception_id FROM ins),md5($1 || ':approval_prewrite_failed')::uuid) exception_id,status", options: { queryReplacement: `={{ [$("Consume Approval").first().json.idempotency_key] }}` } }, { credentials: pgCred });
      add('Approval Exception Response', 'n8n-nodes-base.respondToWebhook', 1.4, 2160, 760, { respondWith: 'json', responseBody: '={{ {status:"exception",exception_id:$json.exception_id} }}', options: { responseCode: 409 } });
      connect(connections, 'Build Bounded Operation', 'Prepare Duplicate Check'); connect(connections, 'Prepare Duplicate Check', 'Check Existing Odoo', 0); connect(connections, 'Prepare Duplicate Check', 'Queue Approval Exception', 1); connect(connections, 'Decode Duplicate Check', 'Classify Duplicate', 0); connect(connections, 'Decode Duplicate Check', 'Queue Approval Exception', 1); connect(connections, 'Classify Duplicate', 'No Existing?', 0); connect(connections, 'Classify Duplicate', 'Queue Approval Exception', 1); connect(connections, 'No Existing?', 'Create Odoo Record', 0); connect(connections, 'No Existing?', 'Complete Duplicate', 1); connect(connections, 'Create Odoo Record', 'Decode Created Record', 0); connect(connections, 'Create Odoo Record', 'Queue Uncertain', 1); connect(connections, 'Decode Created Record', 'Prepare Verification', 0); connect(connections, 'Decode Created Record', 'Queue Uncertain', 1); connect(connections, 'Prepare Verification', 'Verify Odoo Record', 0); connect(connections, 'Prepare Verification', 'Queue Uncertain', 1); connect(connections, 'Verify Odoo Record', 'Decode Verification', 0); connect(connections, 'Verify Odoo Record', 'Queue Uncertain', 1); connect(connections, 'Decode Verification', 'Verify Postcondition', 0); connect(connections, 'Decode Verification', 'Queue Uncertain', 1); connect(connections, 'Verify Postcondition', 'Complete', 0); connect(connections, 'Verify Postcondition', 'Queue Uncertain', 1); connect(connections, 'Complete Duplicate', 'Approval Response'); connect(connections, 'Queue Approval Exception', 'Approval Exception Response'); connect(connections, 'Queue Approval Exception', 'Alert Owner');
      add('Queue Uncertain', 'n8n-nodes-base.postgres', 2.6, 2640, 680, { operation: 'executeQuery', query: "WITH ins AS (INSERT INTO phase8.exceptions(exception_id,idempotency_key,error_class,reason_code,owner) SELECT md5($1 || ':odoo_write_or_verify_uncertain')::uuid,$1,'uncertain','odoo_write_or_verify_uncertain',owner FROM phase8.events WHERE idempotency_key=$1 ON CONFLICT (exception_id) DO NOTHING RETURNING exception_id) UPDATE phase8.events SET status='uncertain',updated_at=now() WHERE idempotency_key=$1 RETURNING COALESCE((SELECT exception_id FROM ins),md5($1 || ':odoo_write_or_verify_uncertain')::uuid) exception_id,status", options: { queryReplacement: `={{ [$("Consume Approval").first().json.idempotency_key] }}` } }, { credentials: pgCred });
      add('Uncertain Response', 'n8n-nodes-base.respondToWebhook', 1.4, 2880, 680, { respondWith: 'json', responseBody: '={{ {status:"uncertain",exception_id:$json.exception_id} }}', options: { responseCode: 409 } }); connect(connections, 'Queue Uncertain', 'Uncertain Response'); connect(connections, 'Queue Uncertain', 'Alert Owner');
    }
    add('Approval Response', 'n8n-nodes-base.respondToWebhook', 1.4, 1920, 440, { respondWith: 'json', responseBody: '={{ $json }}', options: { responseCode: 200 } });
    add('Rejected Response', 'n8n-nodes-base.respondToWebhook', 1.4, 960, 600, { respondWith: 'json', responseBody: '={{ {status:"rejected_or_invalid"} }}', options: { responseCode: 409 } });
    connect(connections, 'Approval Trigger', 'Validate Approval'); connect(connections, 'Validate Approval', 'Consume Approval'); connect(connections, 'Consume Approval', 'Approved?'); connect(connections, 'Approved?', spec.signoff ? 'Complete' : 'Build Bounded Operation', 0); connect(connections, 'Approved?', 'Rejected Response', 1); connect(connections, 'Complete', 'Approval Response');
  }

  return { name: spec.name, nodes, connections, active: false, settings: { executionOrder: 'v1', timezone: 'Asia/Jakarta', saveDataErrorExecution: 'none', saveDataSuccessExecution: 'none', saveManualExecutions: false, executionTimeout: 300 }, versionId: uuid(`${spec.slug}:version`), meta: { templateCredsSetupCompleted: false, phase: 8, schemaVersion: '1.0', productionApproved: false }, tags: [] };
}

mkdirSync(out, { recursive: true });
let changed = false;
for (const spec of specs) {
  const path = resolve(out, `${spec.slug}.v1.json`);
  const content = `${JSON.stringify(workflow(spec), null, 2)}\n`;
  if (check) {
    try { if (readFileSync(path, 'utf8') !== content) changed = true; }
    catch { changed = true; }
  } else writeFileSync(path, content);
}
if (changed) { console.error('generated workflow exports are stale'); process.exit(1); }
console.log(`${check ? 'verified' : 'generated'} ${specs.length} workflow exports`);
